version: '3.7'

services:
  idempiere:
    image: idempiere:${IDEMPIERE_VERSION}
    ports:
      - 8080:8080
      - 8443:8443
      - 12612:12612

  postgres:
    image: postgres:9.6
    volumes:
      - idempiere_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_ADMIN_PASS}
    ports:
      - 5432:5432

volumes:
  idempiere_data:
